#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This module loads a `requirements.txt` and uses `virtualenv`/`pip` to
install the required Python packages into the specified directory.

Inspired by: https://github.com/awslabs/chalice

Author: Logan Raarup <logan@logan.dk>
"""
import ipaddress
import os
import platform
import re
import shlex
import shutil
import socket
import subprocess
import sys
from urllib.parse import urlparse

try:
    import virtualenv
except ImportError:  # pragma: no cover
    sys.exit("Unable to load virtualenv, please install")


PIP_COMPILE_LOCK_HEADER = re.compile(
    r"^#\s+This file is autogenerated by pip-compile", re.MULTILINE
)

SSRF_ALLOWED_HOST_PATTERNS = [
    re.compile(r"^.*\.pypi\.org$"),
    re.compile(r"^pypi\.org$"),
    re.compile(r"^.*\.pythonhosted\.org$"),
    re.compile(r"^pythonhosted\.org$"),
    re.compile(r"^files\.pythonhosted\.org$"),
    re.compile(r"^.*amazonaws\.com$"),
    re.compile(r"^localhost$"),
    re.compile(r"^127\.0\.0\.1$"),
]

SSRF_ALLOWED_PRIVATE_NETWORKS = [
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
    ipaddress.ip_network("127.0.0.0/8"),
    ipaddress.ip_network("::1/128"),
    ipaddress.ip_network("fc00::/7"),
    ipaddress.ip_network("fe80::/10"),
]


def _is_pip_compile_lock(filepath):
    if not os.path.isfile(filepath):
        return False
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            head = f.read(4096)
        return bool(PIP_COMPILE_LOCK_HEADER.search(head))
    except (OSError, IOError):
        return False


def _parse_requirements_packages(filepath):
    packages = set()
    if not os.path.isfile(filepath):
        return packages
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line or line.startswith("#"):
                    continue
                if line.startswith("-") or line.startswith("--"):
                    continue
                pkg_name = re.split(r"[<>=!~; \[]", line, 1)[0].strip()
                if pkg_name:
                    packages.add(pkg_name.lower())
    except (OSError, IOError):
        pass
    return packages


def check_lock_drift(req_file, lock_file, ci_mode=False):
    if not os.path.isfile(lock_file):
        return
    req_packages = _parse_requirements_packages(req_file)
    lock_packages = _parse_requirements_packages(lock_file)
    missing_in_lock = req_packages - lock_packages
    extra_in_lock = lock_packages - req_packages
    if missing_in_lock or extra_in_lock:
        drift_msg = (
            "Lock file drift detected between {} and {}. ".format(
                req_file, lock_file
            )
        )
        if missing_in_lock:
            drift_msg += "In requirements.txt but not in lock: {}. ".format(
                ", ".join(sorted(missing_in_lock))
            )
        if extra_in_lock:
            drift_msg += "In lock but not in requirements.txt (expected for transitive deps): {}. ".format(
                ", ".join(sorted(extra_in_lock))
            )
        drift_msg += "Run pip-compile to regenerate the lockfile."
        if ci_mode:
            sys.exit("ERROR: " + drift_msg)
        else:
            sys.stderr.write("WARNING: " + drift_msg + "\n")


def _resolve_ip_addresses(host):
    try:
        infos = socket.getaddrinfo(host, None)
        return {ipaddress.ip_address(info[4][0]) for info in infos}
    except socket.gaierror:
        return set()


def _is_private_ip(ip_addr):
    for network in SSRF_ALLOWED_PRIVATE_NETWORKS:
        if ip_addr in network:
            return True
    return False


def validate_index_url(url, allowed_host_patterns=None):
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https"):
        sys.exit(
            "ERROR: Invalid scheme in PyPI index URL '{}'. Only http/https allowed.".format(
                url
            )
        )
    host = parsed.hostname
    if not host:
        sys.exit("ERROR: Missing host in PyPI index URL '{}'.".format(url))
    host_lower = host.lower()
    patterns = allowed_host_patterns or SSRF_ALLOWED_HOST_PATTERNS
    for pattern in patterns:
        if pattern.match(host_lower):
            return
    ips = _resolve_ip_addresses(host_lower)
    if ips:
        for ip in ips:
            if _is_private_ip(ip):
                sys.exit(
                    "ERROR: PyPI index URL '{}' resolves to private/internal IP {} (SSRF protection).".format(
                        url, ip
                    )
                )
    custom_whitelist = os.environ.get("WSGI_PYPI_HOST_WHITELIST", "")
    if custom_whitelist:
        for entry in custom_whitelist.split(","):
            entry = entry.strip().lower()
            if not entry:
                continue
            if re.match(r"^\*", entry):
                pat = re.compile(r"^.*" + re.escape(entry.lstrip("*")) + r"$")
            else:
                pat = re.compile(r"^" + re.escape(entry) + r"$")
            if pat.match(host_lower):
                return
    sys.exit(
        "ERROR: PyPI index URL host '{}' is not in the allowed whitelist (SSRF protection).".format(
            host
        )
    )


def build_pip_install_args(extra_index_urls=None):
    args = []
    if extra_index_urls:
        for url in extra_index_urls:
            validate_index_url(url)
            args.extend(["--extra-index-url", url])
    return args


def locate_lockfile(req_file):
    base_dir = os.path.dirname(os.path.abspath(req_file))
    candidate_names = ["requirements.lock", "requirements-lock.txt"]
    for name in candidate_names:
        candidate = os.path.join(base_dir, name)
        if _is_pip_compile_lock(candidate):
            return candidate
    return None


def package(
    req_files,
    target_dir,
    pip_args="",
    extra_index_urls=None,
    ci_mode=False,
):
    venv_dir = os.path.join(target_dir, ".venv")
    tmp_dir = os.path.join(target_dir, ".tmp")

    resolved_req_files = []
    for req_file in req_files:
        if not os.path.isfile(req_file):
            sys.exit("No requirements file found in: {}".format(req_file))
        lock_file = locate_lockfile(req_file)
        if lock_file:
            check_lock_drift(req_file, lock_file, ci_mode=ci_mode)
            resolved_req_files.append(lock_file)
        else:
            resolved_req_files.append(req_file)

    if os.path.exists(target_dir):
        if not os.path.isdir(target_dir):
            sys.exit("Existing non-directory found at: {}".format(target_dir))
        shutil.rmtree(target_dir)
    os.mkdir(target_dir)

    if os.path.exists(venv_dir):
        shutil.rmtree(venv_dir)

    if os.path.exists(tmp_dir):
        shutil.rmtree(tmp_dir)

    if hasattr(virtualenv, "main"):
        original = sys.argv
        sys.argv = ["", venv_dir, "--quiet", "-p", sys.executable]
        try:
            virtualenv.main()
        finally:
            sys.argv = original
    else:
        virtualenv.cli_run([venv_dir, "--quiet", "-p", sys.executable])

    if platform.system() == "Windows":
        pip_exe = os.path.join(venv_dir, "Scripts", "pip.exe")
        deps_dir = os.path.join(venv_dir, "Lib", "site-packages")
    else:
        pip_exe = os.path.join(venv_dir, "bin", "pip")
        lib_path = os.path.join(venv_dir, "lib")
        libs_dir_path_items = os.listdir(lib_path)
        directories = [
            d for d in libs_dir_path_items if os.path.isdir(os.path.join(lib_path, d))
        ]
        if len(directories) > 0:
            python_dir = directories[0]
        else:
            sys.exit("No python directory")
        deps_dir = os.path.join(venv_dir, "lib", python_dir, "site-packages")

    if not os.path.isfile(pip_exe):
        sys.exit("Pip not found in: {}".format(pip_exe))

    extra_pip_args = build_pip_install_args(extra_index_urls)

    for req_file in resolved_req_files:
        cmd = [pip_exe, "install", "-r", req_file] + extra_pip_args + shlex.split(pip_args)
        p = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        stdout, stderr = p.communicate()
        if p.returncode != 0:
            sys.stderr.write(stderr.decode("utf-8", errors="replace"))
            sys.exit("Failed to install requirements from: {}".format(req_file))

    if not os.path.isdir(deps_dir):
        sys.exit("Installed packages not found in: {}".format(deps_dir))

    blacklist = [
        "pip",
        "pip-*",
        "wheel",
        "wheel-*",
        "setuptools",
        "setuptools-*",
        "*.dist-info",
        "easy_install.*",
        "*.pyc",
        "__pycache__",
        "_virtualenv.*",
        "distutils-precedence.pth",
        "six.py",
        "zipp.py"
    ]

    shutil.copytree(
        deps_dir, tmp_dir, symlinks=False, ignore=shutil.ignore_patterns(*blacklist)
    )
    for f in os.listdir(tmp_dir):
        target = os.path.join(target_dir, f)
        if os.path.isdir(target):
            shutil.rmtree(target)
        elif os.path.exists(target):
            os.remove(target)
        shutil.move(os.path.join(tmp_dir, f), target_dir)
    shutil.rmtree(venv_dir)
    shutil.rmtree(tmp_dir)


if __name__ == "__main__":  # pragma: no cover
    args = sys.argv
    pip_args = ""
    extra_index_urls = []
    ci_mode = False

    consumed = []
    i = 1
    while i < len(args):
        a = args[i]
        if a == "--pip-args":
            if i + 1 >= len(args):
                sys.exit("--pip-args requires a value")
            pip_args = args[i + 1]
            i += 2
            continue
        if a == "--extra-index-url":
            if i + 1 >= len(args):
                sys.exit("--extra-index-url requires a value")
            extra_index_urls.append(args[i + 1])
            i += 2
            continue
        if a == "--ci":
            ci_mode = True
            i += 1
            continue
        consumed.append(a)
        i += 1
    args = consumed

    if len(args) < 2:
        sys.exit(
            "Usage: {} --pip-args '--no-deps' --extra-index-url URL --ci REQ_FILE... TARGET_DIR".format(
                os.path.basename(sys.argv[0])
            )
        )

    package(args[:-1], args[-1], pip_args, extra_index_urls, ci_mode)
